# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\generacion.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_generation_ui(object):
    def setupUi(self, generation_ui):
        generation_ui.setObjectName("generation_ui")
        generation_ui.resize(735, 360)
        self.groupBox = QtWidgets.QGroupBox(generation_ui)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 351, 341))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 331, 61))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.path_Label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.path_Label.setObjectName("path_Label")
        self.verticalLayout.addWidget(self.path_Label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.iterations_Label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.iterations_Label.setObjectName("iterations_Label")
        self.horizontalLayout.addWidget(self.iterations_Label)
        self.population_Label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.population_Label.setObjectName("population_Label")
        self.horizontalLayout.addWidget(self.population_Label)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.originalPic_Viewer = QtWidgets.QLabel(self.groupBox)
        self.originalPic_Viewer.setGeometry(QtCore.QRect(14, 95, 321, 231))
        self.originalPic_Viewer.setScaledContents(True)
        self.originalPic_Viewer.setObjectName("originalPic_Viewer")
        self.groupBox_2 = QtWidgets.QGroupBox(generation_ui)
        self.groupBox_2.setGeometry(QtCore.QRect(370, 10, 351, 341))
        self.groupBox_2.setObjectName("groupBox_2")
        self.progressBar = QtWidgets.QProgressBar(self.groupBox_2)
        self.progressBar.setGeometry(QtCore.QRect(10, 40, 331, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.generatedPic_View = QtWidgets.QLabel(self.groupBox_2)
        self.generatedPic_View.setGeometry(QtCore.QRect(10, 100, 331, 231))
        self.generatedPic_View.setScaledContents(True)
        self.generatedPic_View.setObjectName("generatedPic_View")

        self.retranslateUi(generation_ui)
        QtCore.QMetaObject.connectSlotsByName(generation_ui)

    def retranslateUi(self, generation_ui):
        _translate = QtCore.QCoreApplication.translate
        generation_ui.setWindowTitle(_translate("generation_ui", "Dialog"))
        self.groupBox.setTitle(_translate("generation_ui", "Imagen Original"))
        self.path_Label.setText(_translate("generation_ui", "Path:"))
        self.iterations_Label.setText(_translate("generation_ui", "Iteraciones:"))
        self.population_Label.setText(_translate("generation_ui", "Población:"))
        self.originalPic_Viewer.setText(_translate("generation_ui", "TextLabel"))
        self.groupBox_2.setTitle(_translate("generation_ui", "Imagen Generada"))
        self.generatedPic_View.setText(_translate("generation_ui", "TextLabel"))
