# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Del Píxel al Pincel - Propiedades.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_properties_Dialog(object):
    def setupUi(self, properties_Dialog):
        properties_Dialog.setObjectName("properties_Dialog")
        properties_Dialog.resize(404, 360)
        self.imageSelection_Box = QtWidgets.QGroupBox(properties_Dialog)
        self.imageSelection_Box.setGeometry(QtCore.QRect(10, 10, 381, 61))
        self.imageSelection_Box.setObjectName("imageSelection_Box")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.imageSelection_Box)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 361, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.imagePath_textInput = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.imagePath_textInput.setObjectName("imagePath_textInput")
        self.horizontalLayout.addWidget(self.imagePath_textInput)
        self.imageSearch_Button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.imageSearch_Button.setObjectName("imageSearch_Button")
        self.horizontalLayout.addWidget(self.imageSearch_Button)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(properties_Dialog)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 150, 361, 201))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.imagePreview_View = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.imagePreview_View.setText("")
        self.imagePreview_View.setScaledContents(True)
        self.imagePreview_View.setObjectName("imagePreview_View")
        self.horizontalLayout_2.addWidget(self.imagePreview_View)
        self.generate_Button = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.generate_Button.setObjectName("generate_Button")
        self.horizontalLayout_2.addWidget(self.generate_Button)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(properties_Dialog)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 70, 381, 51))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.iteration_Box = QtWidgets.QGroupBox(self.horizontalLayoutWidget_3)
        self.iteration_Box.setObjectName("iteration_Box")
        self.iteration_spinBox = QtWidgets.QSpinBox(self.iteration_Box)
        self.iteration_spinBox.setGeometry(QtCore.QRect(10, 20, 101, 24))
        self.iteration_spinBox.setMaximum(50)
        self.iteration_spinBox.setObjectName("iteration_spinBox")
        self.horizontalLayout_3.addWidget(self.iteration_Box)
        self.population_Box = QtWidgets.QGroupBox(self.horizontalLayoutWidget_3)
        self.population_Box.setObjectName("population_Box")
        self.population_spinBox = QtWidgets.QSpinBox(self.population_Box)
        self.population_spinBox.setGeometry(QtCore.QRect(10, 20, 101, 24))
        self.population_spinBox.setMaximum(250)
        self.population_spinBox.setObjectName("population_spinBox")
        self.horizontalLayout_3.addWidget(self.population_Box)
        self.gama_box = QtWidgets.QGroupBox(self.horizontalLayoutWidget_3)
        self.gama_box.setObjectName("gama_box")
        self.gama_combobox = QtWidgets.QComboBox(self.gama_box)
        self.gama_combobox.setGeometry(QtCore.QRect(10, 20, 101, 22))
        self.gama_combobox.setObjectName("gama_combobox")
        self.horizontalLayout_3.addWidget(self.gama_box)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(properties_Dialog)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(20, 120, 361, 31))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.resize_checkb = QtWidgets.QCheckBox(self.horizontalLayoutWidget_4)
        self.resize_checkb.setObjectName("resize_checkb")
        self.horizontalLayout_4.addWidget(self.resize_checkb)
        self.median_checkb = QtWidgets.QCheckBox(self.horizontalLayoutWidget_4)
        self.median_checkb.setObjectName("median_checkb")
        self.horizontalLayout_4.addWidget(self.median_checkb)
        self.gauss_checkb = QtWidgets.QCheckBox(self.horizontalLayoutWidget_4)
        self.gauss_checkb.setObjectName("gauss_checkb")
        self.horizontalLayout_4.addWidget(self.gauss_checkb)

        self.retranslateUi(properties_Dialog)
        QtCore.QMetaObject.connectSlotsByName(properties_Dialog)

    def retranslateUi(self, properties_Dialog):
        _translate = QtCore.QCoreApplication.translate
        properties_Dialog.setWindowTitle(_translate("properties_Dialog", "Dialog"))
        self.imageSelection_Box.setTitle(_translate("properties_Dialog", "Selección de Imagen"))
        self.imageSearch_Button.setText(_translate("properties_Dialog", "Buscar imagen"))
        self.generate_Button.setText(_translate("properties_Dialog", "Transformar \n"
"Imagen"))
        self.iteration_Box.setTitle(_translate("properties_Dialog", "Iteraciones"))
        self.population_Box.setTitle(_translate("properties_Dialog", "Población"))
        self.gama_box.setTitle(_translate("properties_Dialog", "Gama y brillo"))
        self.resize_checkb.setText(_translate("properties_Dialog", "Resize"))
        self.median_checkb.setText(_translate("properties_Dialog", "Median"))
        self.gauss_checkb.setText(_translate("properties_Dialog", "Gauss"))
